"""Go code generator for AXON.

Compiles AXON declarations (agents, tools, type aliases) to Go source code
for server-side runtime targets. Generated code includes:
- Go structs for record type aliases
- Function signatures for tools with stub implementations
- Agent structs with method stubs
- Result/Option helper types

The generated code is meant to be runnable after the user fills in tool bodies.
"""

from __future__ import annotations

import re
from typing import Any

from axon.ast_nodes import AgentDecl, MethodDecl, Param, ToolDecl, TypeAliasDecl
from axon.codegen.mcp import to_snake_case


def generate_go(
    declarations: list,
    output_name: str = "axon_app",
) -> str:
    """Generate a Go source file from AXON declarations.

    Args:
        declarations: output of parse() from parser.py
        output_name: used for the generated package name

    Returns:
        A Go source string ready to be written to a .go file.
    """
    tools = [d for d in declarations if isinstance(d, ToolDecl)]
    agents = [d for d in declarations if isinstance(d, AgentDecl)]
    types = [d for d in declarations if isinstance(d, TypeAliasDecl)]
    agent = agents[0] if agents else None

    package = to_snake_case(output_name).replace("-", "_")
    lines: list[str] = []
    lines.append(f"// Code generated by AXON Go target from {output_name}. DO NOT EDIT.")
    lines.append(f"// Regenerate with: axon build --target go {output_name}.ax")
    lines.append(f"package {package}")
    lines.append("")
    lines.append("import (")
    lines.append('\t"context"')
    lines.append('\t"fmt"')
    lines.append(')')
    lines.append("")

    # Result and Option types
    lines.append("// ── Result / Option helpers ──────────────────────────────────────────────────")
    lines.append("")
    lines.extend(_result_option_types())
    lines.append("")

    # Type aliases as Go structs
    if types:
        lines.append("// ── Type Aliases ──────────────────────────────────────────────────────────────")
        lines.append("")
        for ta in types:
            lines.extend(_generate_type_alias(ta))
            lines.append("")

    # Tool functions
    if tools:
        lines.append("// ── Tools ─────────────────────────────────────────────────────────────────────")
        lines.append("")
        for tool in tools:
            lines.extend(_generate_tool_func(tool))
            lines.append("")

    # Agent struct
    if agent:
        lines.append("// ── Agent ─────────────────────────────────────────────────────────────────────")
        lines.append("")
        lines.extend(_generate_agent_struct(agent))
        lines.append("")

    return "\n".join(lines)


def _axon_type_to_go(axon_type: str) -> str:
    """Map AXON types to Go types."""
    axon_type = axon_type.strip()
    if not axon_type:
        return "any"

    primitives = {
        "Str": "string",
        "Int": "int64",
        "Float": "float64",
        "Bool": "bool",
        "Any": "any",
        "Bytes": "[]byte",
        "()": "struct{}",
    }
    if axon_type in primitives:
        return primitives[axon_type]

    generic = _parse_generic(axon_type)
    if generic:
        name, args = generic
        if name == "List" and len(args) == 1:
            return f"[]{_axon_type_to_go(args[0])}"
        if name == "Set" and len(args) == 1:
            return f"map[{_axon_type_to_go(args[0])}]struct{{}}"
        if name == "Map" and len(args) == 2:
            return f"map[{_axon_type_to_go(args[0])}]{_axon_type_to_go(args[1])}"
        if name == "Option" and len(args) == 1:
            return f"*{_axon_type_to_go(args[0])}"
        if name == "Result" and len(args) >= 1:
            ok_type = _axon_type_to_go(args[0])
            err_type = _axon_type_to_go(args[1]) if len(args) > 1 else "error"
            return f"Result[{ok_type}, {err_type}]"

    # Union types (literal unions) -> string
    if "|" in axon_type and '"' in axon_type:
        return "string"

    # Unknown types — pass through as-is (may be user-defined types)
    return axon_type


def _parse_generic(type_expr: str) -> tuple[str, list[str]] | None:
    if "<" not in type_expr:
        return None
    name = type_expr[: type_expr.index("<")].strip()
    inner = type_expr[type_expr.index("<") + 1 : type_expr.rindex(">")]
    args = _split_type_args(inner)
    return name, args


def _split_type_args(s: str) -> list[str]:
    args: list[str] = []
    depth = 0
    current = ""
    for ch in s:
        if ch == "<":
            depth += 1
            current += ch
        elif ch == ">":
            depth -= 1
            current += ch
        elif ch == "," and depth == 0:
            args.append(current.strip())
            current = ""
        else:
            current += ch
    if current.strip():
        args.append(current.strip())
    return args


def _result_option_types() -> list[str]:
    return [
        "type Result[T any, E any] struct {",
        "\tOk  T",
        "\tErr E",
        "\tIsErr bool",
        "}",
        "",
        "func (r Result[T, E]) Unwrap() T {",
        "\tif r.IsErr {",
        "\t\tpanic(fmt.Sprintf(\"unwrap error: %v\", r.Err))",
        "\t}",
        "\treturn r.Ok",
        "}",
        "",
        "func (r Result[T, E]) UnwrapOr(def T) T {",
        "\tif r.IsErr {",
        "\t\treturn def",
        "\t}",
        "\treturn r.Ok",
        "}",
        "",
        "func OkResult[T any](v T) Result[T, error] {",
        "\treturn Result[T, error]{Ok: v}",
        "}",
        "",
        "func ErrResult[T any](err error) Result[T, error] {",
        "\treturn Result[T, error]{IsErr: true, Err: err}",
        "}",
    ]


def _generate_type_alias(ta: TypeAliasDecl) -> list[str]:
    lines: list[str] = []
    if ta.fields:
        lines.append(f"type {ta.name} struct {{")
        for f in ta.fields:
            go_type = _axon_type_to_go(f.type_str)
            field_name = _to_exported_name(f.name)
            lines.append(f"\t{field_name} {go_type} `json:\"{f.name}\"`")
        lines.append("}")
    else:
        go_type = _axon_type_to_go(ta.value)
        lines.append(f"type {ta.name} = {go_type}")
    return lines


def _generate_tool_func(tool: ToolDecl) -> list[str]:
    func_name = _to_exported_name(tool.name)
    params = ", ".join(_param_to_go(p) for p in tool.params)
    ret = _axon_type_to_go(tool.return_type)

    lines: list[str] = []
    if tool.docstrings:
        lines.append(f"// {func_name} — {tool.docstrings[0]}")
    lines.append(f"func {func_name}(ctx context.Context, {params}) ({ret}, error) {{")
    lines.append(f"\t// TODO: implement {tool.name}")
    lines.append(f"\t// AXON source: {tool.name}({_axon_params_str(tool.params)}) -> {tool.return_type}")
    if tool.body.strip():
        for body_line in tool.body.strip().split("\n"):
            lines.append(f"\t// AXON body: {body_line}")
    lines.append(f"\treturn _zero[{ret}](), fmt.Errorf(\"{tool.name} not implemented\")")
    lines.append("}")
    return lines


def _param_to_go(p: Param) -> str:
    go_type = _axon_type_to_go(p.type_str)
    return f"{p.name} {go_type}"


def _axon_params_str(params: list[Param]) -> str:
    return ", ".join(f"{p.name}: {p.type_str}" for p in params)


def _generate_agent_struct(agent: AgentDecl) -> list[str]:
    struct_name = agent.name
    lines: list[str] = []
    lines.append(f"type {struct_name} struct {{")
    lines.append(f'\tModel  string')
    lines.append(f'\tTools  []string')
    lines.append(f'\tVersion string')
    lines.append("}")
    lines.append("")
    lines.append(f"func New{struct_name}() *{struct_name} {{")
    lines.append(f'\treturn &{struct_name}{{')
    lines.append(f'\t\tModel:  "{_escape_go_string(agent.model)}",')
    lines.append(f'\t\tTools:  []string{{{", ".join(repr(t) for t in agent.tools)}}},')
    lines.append(f'\t\tVersion: "{_escape_go_string(agent.version)}",')
    lines.append(f'\t}}')
    lines.append("}")
    lines.append("")

    for method in agent.methods:
        lines.extend(_generate_method(struct_name, method))
        lines.append("")

    return lines


def _generate_method(struct_name: str, method: MethodDecl) -> list[str]:
    func_name = _to_exported_name(method.name)
    params = ", ".join(_param_to_go(p) for p in method.params)
    ret = _axon_type_to_go(method.return_type)

    lines: list[str] = []
    lines.append(f"func (a *{struct_name}) {func_name}(ctx context.Context, {params}) ({ret}, error) {{")
    lines.append(f"\t// TODO: implement {method.name}")
    lines.append(f"\treturn _zero[{ret}](), fmt.Errorf(\"{method.name} not implemented\")")
    lines.append("}")
    return lines


def _to_exported_name(name: str) -> str:
    if not name:
        return name
    parts = re.split(r"[_\-\s]+", name)
    return "".join(p[0].upper() + p[1:] for p in parts if p)


def _escape_go_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _zero_func() -> list[str]:
    return [
        "func _zero[T any]() T {",
        "\tvar z T",
        "\treturn z",
        "}",
    ]
