"""Rust code generator for AXON.

Compiles AXON declarations (agents, tools, type aliases) to Rust source code
for native runtime targets. Generated code includes:
- Rust structs for record type aliases
- Function signatures for tools with stub implementations
- Agent structs with method stubs
- Result/Option helpers (using std::result::Result)

The generated code is meant to be runnable after the user fills in tool bodies.
"""

from __future__ import annotations

import re
from typing import Any

from axon.ast_nodes import AgentDecl, MethodDecl, Param, ToolDecl, TypeAliasDecl
from axon.codegen.mcp import to_snake_case


def generate_rust(
    declarations: list,
    output_name: str = "axon_app",
) -> str:
    """Generate a Rust source file from AXON declarations.

    Args:
        declarations: output of parse() from parser.py
        output_name: used for the generated module name

    Returns:
        A Rust source string ready to be written to a .rs file.
    """
    tools = [d for d in declarations if isinstance(d, ToolDecl)]
    agents = [d for d in declarations if isinstance(d, AgentDecl)]
    types = [d for d in declarations if isinstance(d, TypeAliasDecl)]
    agent = agents[0] if agents else None

    mod_name = to_snake_case(output_name).replace("-", "_")
    lines: list[str] = []
    lines.append(f"// Code generated by AXON Rust target from {output_name}. DO NOT EDIT.")
    lines.append(f"// Regenerate with: axon build --target rust {output_name}.ax")
    lines.append("")
    lines.append(f"pub mod {mod_name} {{")
    lines.append("")
    lines.append("    use std::collections::{HashMap, HashSet};")
    lines.append("    use std::error::Error;")
    lines.append("    use std::fmt;")
    lines.append("")

    # Type aliases as Rust structs
    if types:
        lines.append("    // ── Type Aliases ──────────────────────────────────────────────────────────")
        lines.append("")
        for ta in types:
            lines.extend(_indent(_generate_type_alias(ta)))
            lines.append("")

    # Tool functions
    if tools:
        lines.append("    // ── Tools ─────────────────────────────────────────────────────────────────")
        lines.append("")
        for tool in tools:
            lines.extend(_indent(_generate_tool_fn(tool)))
            lines.append("")

    # Agent struct
    if agent:
        lines.append("    // ── Agent ─────────────────────────────────────────────────────────────────")
        lines.append("")
        lines.extend(_indent(_generate_agent_struct(agent)))
        lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _axon_type_to_rust(axon_type: str) -> str:
    """Map AXON types to Rust types."""
    axon_type = axon_type.strip()
    if not axon_type:
        return "()"

    primitives = {
        "Str": "String",
        "Int": "i64",
        "Float": "f64",
        "Bool": "bool",
        "Any": "serde_json::Value",
        "Bytes": "Vec<u8>",
        "()": "()",
    }
    if axon_type in primitives:
        return primitives[axon_type]

    generic = _parse_generic(axon_type)
    if generic:
        name, args = generic
        if name == "List" and len(args) == 1:
            return f"Vec<{_axon_type_to_rust(args[0])}>"
        if name == "Set" and len(args) == 1:
            return f"HashSet<{_axon_type_to_rust(args[0])}>"
        if name == "Map" and len(args) == 2:
            return f"HashMap<{_axon_type_to_rust(args[0])}, {_axon_type_to_rust(args[1])}>"
        if name == "Option" and len(args) == 1:
            return f"Option<{_axon_type_to_rust(args[0])}>"
        if name == "Result" and len(args) >= 1:
            ok_type = _axon_type_to_rust(args[0])
            err_type = _axon_type_to_rust(args[1]) if len(args) > 1 else "Box<dyn Error>"
            return f"Result<{ok_type}, {err_type}>"
        if name == "Stream" and len(args) == 1:
            return f"Vec<{_axon_type_to_rust(args[0])}>"

    # Union types (literal unions) -> String
    if "|" in axon_type and '"' in axon_type:
        return "String"

    # Unknown types -> use as-is (may be a user-defined type)
    return axon_type


def _parse_generic(type_expr: str) -> tuple[str, list[str]] | None:
    if "<" not in type_expr:
        return None
    name = type_expr[: type_expr.index("<")].strip()
    inner = type_expr[type_expr.index("<") + 1 : type_expr.rindex(">")]
    args = _split_type_args(inner)
    return name, args


def _split_type_args(s: str) -> list[str]:
    args: list[str] = []
    depth = 0
    current = ""
    for ch in s:
        if ch == "<":
            depth += 1
            current += ch
        elif ch == ">":
            depth -= 1
            current += ch
        elif ch == "," and depth == 0:
            args.append(current.strip())
            current = ""
        else:
            current += ch
    if current.strip():
        args.append(current.strip())
    return args


def _generate_type_alias(ta: TypeAliasDecl) -> list[str]:
    lines: list[str] = []
    if ta.fields:
        lines.append("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]")
        lines.append(f"pub struct {ta.name} {{")
        for f in ta.fields:
            rust_type = _axon_type_to_rust(f.type_str)
            if f.default is not None:
                lines.append(f"    pub {f.name}: {rust_type},")
            else:
                lines.append(f"    pub {f.name}: {rust_type},")
        lines.append("}")
    else:
        rust_type = _axon_type_to_rust(ta.value)
        lines.append(f"pub type {ta.name} = {rust_type};")
    return lines


def _generate_tool_fn(tool: ToolDecl) -> list[str]:
    func_name = to_snake_case(tool.name)
    params = ", ".join(_param_to_rust(p) for p in tool.params)
    ret = _axon_type_to_rust(tool.return_type)

    lines: list[str] = []
    if tool.docstrings:
        lines.append(f"/// {tool.docstrings[0]}")
    lines.append(f"pub fn {func_name}({params}) -> Result<{ret}, Box<dyn Error>> {{")
    lines.append(f"    // TODO: implement {tool.name}")
    lines.append(f"    // AXON source: {tool.name}({_axon_params_str(tool.params)}) -> {tool.return_type}")
    if tool.body.strip():
        for body_line in tool.body.strip().split("\n"):
            lines.append(f"    // AXON body: {body_line}")
    lines.append(f'    Err(format!("{tool.name} not implemented")?.into())')
    lines.append("}")
    return lines


def _param_to_rust(p: Param) -> str:
    rust_type = _axon_type_to_rust(p.type_str)
    return f"{p.name}: {rust_type}"


def _axon_params_str(params: list[Param]) -> str:
    return ", ".join(f"{p.name}: {p.type_str}" for p in params)


def _generate_agent_struct(agent: AgentDecl) -> list[str]:
    struct_name = agent.name
    lines: list[str] = []
    lines.append("#[derive(Debug, Clone)]")
    lines.append(f"pub struct {struct_name} {{")
    lines.append(f"    pub model: String,")
    lines.append(f"    pub tools: Vec<String>,")
    lines.append(f"    pub version: String,")
    lines.append("}")
    lines.append("")
    lines.append(f"impl {struct_name} {{")
    lines.append(f"    pub fn new() -> Self {{")
    lines.append(f"        Self {{")
    lines.append(f'            model: "{_escape_rust_string(agent.model)}".to_string(),')
    tools_vec = ", ".join('"{t}".to_string()'.replace("{t}", t) for t in agent.tools)
    lines.append(f"            tools: vec![{tools_vec}],")
    lines.append(f'            version: "{_escape_rust_string(agent.version)}".to_string(),')
    lines.append(f"        }}")
    lines.append(f"    }}")
    lines.append("")

    for method in agent.methods:
        lines.extend(_generate_method(struct_name, method))
        lines.append("")

    lines.append("}")
    return lines


def _generate_method(struct_name: str, method: MethodDecl) -> list[str]:
    func_name = to_snake_case(method.name)
    params = ", ".join(f"self, {_param_to_rust(p)}" for p in method.params)
    if not method.params:
        params = "&self"
    elif params.startswith("self, "):
        pass
    else:
        params = f"&self, {params}"
    ret = _axon_type_to_rust(method.return_type)

    lines: list[str] = []
    lines.append(f"    pub fn {func_name}({params}) -> Result<{ret}, Box<dyn Error>> {{")
    lines.append(f"        // TODO: implement {method.name}")
    lines.append(f'        Err(format!("{method.name} not implemented")?.into())')
    lines.append("    }")
    return lines


def _indent(lines: list[str], level: int = 1) -> list[str]:
    prefix = "    " * level
    return [f"{prefix}{line}" if line else line for line in lines]


def _escape_rust_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')
