"""TypeScript code generator for AXON.

Compiles AXON declarations (agents, tools, flows) to TypeScript/JavaScript
for browser and Node.js runtimes.  This is the Phase 4 "TypeScript target"
mentioned in the roadmap.
"""

from __future__ import annotations

from typing import Any

from axon.ast_nodes import AgentDecl, Annotation, FlowDecl, Param, StageDecl, ToolDecl


def generate_typescript(
    declarations: list,
    output_name: str = "axon_app",
) -> str:
    """Generate a TypeScript module from AXON declarations.

    Args:
        declarations: output of parse() from parser.py
        output_name: used for the generated module name / class prefix

    Returns:
        A TypeScript source string ready to be written to a .ts file.
    """
    tools = [decl for decl in declarations if isinstance(decl, ToolDecl)]
    agents = [decl for decl in declarations if isinstance(decl, AgentDecl)]
    flows = [decl for decl in declarations if isinstance(decl, FlowDecl)]
    agent = agents[0] if agents else None

    lines: list[str] = []
    lines.append(f"// Generated by AXON TypeScript target from {output_name}")
    lines.append("")
    lines.append("// ── Types ────────────────────────────────────────────────────────────────────")
    lines.append("export type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E };")
    lines.append("export type Option<T> = T | null;")
    lines.append("")

    # Tool interfaces
    if tools:
        lines.append("// ── Tool Interfaces ─────────────────────────────────────────────────────────")
        lines.append("")
        for tool in tools:
            lines.extend(_generate_tool_interface(tool))
            lines.append("")

    # Agent class
    if agent:
        lines.append("// ── Agent Class ──────────────────────────────────────────────────────────────")
        lines.append("")
        lines.extend(_generate_agent_class(agent, tools))
        lines.append("")

    # Flow orchestration
    if flows:
        lines.append("// ── Flow Orchestration ───────────────────────────────────────────────────────")
        lines.append("")
        for flow in flows:
            lines.extend(_generate_flow_class(flow))
            lines.append("")

    # Helper runtime
    lines.append("// ── AXON Runtime Helpers ─────────────────────────────────────────────────────")
    lines.append("")
    lines.extend(_runtime_helpers())
    lines.append("")

    return "\n".join(lines)


def _axon_type_to_ts(axon_type: str) -> str:
    """Map AXON types to TypeScript types."""
    axon_type = axon_type.strip()
    if not axon_type:
        return "any"

    primitives = {
        "Str": "string",
        "Int": "number",
        "Float": "number",
        "Bool": "boolean",
        "Any": "any",
        "Bytes": "Uint8Array",
        "()": "void",
    }
    if axon_type in primitives:
        return primitives[axon_type]

    # Generic types
    generic = _parse_generic(axon_type)
    if generic:
        name, args = generic
        if name == "List" and len(args) == 1:
            return f"Array<{_axon_type_to_ts(args[0])}>"
        if name == "Map" and len(args) == 2:
            return f"Map<{_axon_type_to_ts(args[0])}, {_axon_type_to_ts(args[1])}>"
        if name == "Result" and len(args) >= 1:
            err = _axon_type_to_ts(args[1]) if len(args) > 1 else "Error"
            return f"Result<{_axon_type_to_ts(args[0])}, {err}>"
        if name == "Option" and len(args) == 1:
            return f"Option<{_axon_type_to_ts(args[0])}>"
        if name == "Stream" and len(args) == 1:
            return f"AsyncIterable<{_axon_type_to_ts(args[0])}>"
        if name == "Chan" and len(args) == 1:
            return f"Promise<{_axon_type_to_ts(args[0])}>"

    return "any"


def _parse_generic(type_expr: str) -> tuple[str, list[str]] | None:
    """Parse a generic type like List<Str> into (name, [args])."""
    if "<" not in type_expr:
        return None
    name = type_expr[: type_expr.index("<")].strip()
    inner = type_expr[type_expr.index("<") + 1 : type_expr.rindex(">")]
    args = _split_type_args(inner)
    return name, args


def _split_type_args(s: str) -> list[str]:
    """Split comma-separated type arguments respecting nesting."""
    args: list[str] = []
    depth = 0
    current = ""
    for ch in s:
        if ch == "<":
            depth += 1
            current += ch
        elif ch == ">":
            depth -= 1
            current += ch
        elif ch == "," and depth == 0:
            args.append(current.strip())
            current = ""
        else:
            current += ch
    if current.strip():
        args.append(current.strip())
    return args


def _generate_tool_interface(tool: ToolDecl) -> list[str]:
    """Emit a TypeScript interface for a tool declaration."""
    name = tool.name
    params = tool.params if hasattr(tool, "params") else []
    ret = tool.return_type if hasattr(tool, "return_type") else "Any"

    lines: list[str] = []
    lines.append(f"export interface {name}Input {{")
    for p in params:
        ts_type = _axon_type_to_ts(p.type_str)
        optional = "?" if getattr(p, "default", None) is not None else ""
        lines.append(f"  {p.name}{optional}: {ts_type};")
    lines.append("}")
    lines.append("")
    ret_ts = _axon_type_to_ts(ret)
    lines.append(f"export type {name}Output = {ret_ts};")
    lines.append("")
    lines.append(f"export interface {name} {{")
    lines.append(f"  (input: {name}Input): Promise<{name}Output> | {name}Output;")
    lines.append("}")
    return lines


def _generate_agent_class(agent: AgentDecl, tools: list[ToolDecl]) -> list[str]:
    """Emit a TypeScript class for an agent declaration."""
    name = agent.name
    model = getattr(agent, "model", "@mock/model")
    tool_names = [t.name for t in tools]

    lines: list[str] = []
    lines.append(f"export class {name} {{")
    lines.append(f'  readonly model = "{_escape_ts_string(model)}";')
    if tool_names:
        lines.append(f"  readonly tools = [{', '.join(repr(t) for t in tool_names)}] as const;")
    else:
        lines.append("  readonly tools: string[] = [];")
    lines.append("")
    lines.append("  constructor(private _provider: any = null) {}")
    lines.append("")

    # Emit methods if present
    for method in getattr(agent, "methods", []):
        lines.extend(_generate_agent_method(method))

    lines.append("}")
    return lines


def _generate_agent_method(method) -> list[str]:
    """Emit a TypeScript method from an AXON method declaration."""
    name = method.name
    params = method.params
    ret = method.return_type
    param_list = ", ".join(f"{p.name}: {_axon_type_to_ts(p.type_str)}" for p in params)
    ret_ts = _axon_type_to_ts(ret)

    lines: list[str] = []
    lines.append(f"  async {name}({param_list}): Promise<{ret_ts}> {{")
    lines.append(f"    // TODO: implement {name}")
    lines.append(f'    throw new Error("{name} not implemented");')
    lines.append("  }")
    lines.append("")
    return lines


def _generate_flow_class(flow: FlowDecl) -> list[str]:
    """Emit a TypeScript class for a flow declaration."""
    name = flow.name
    input_type = getattr(flow, "input_type", "Str")
    output_type = getattr(flow, "output_type", "Str")
    stages = getattr(flow, "stages", [])

    lines: list[str] = []
    lines.append(f"export class {name}Flow {{")
    lines.append("  private _stages: Array<(input: any) => any> = [];")
    lines.append("")
    lines.append(f"  constructor() {{")
    for stage in stages:
        lines.append(f"    // stage: {stage.name}")
    lines.append("  }")
    lines.append("")
    lines.append(f"  async run(input: {_axon_type_to_ts(input_type)}): Promise<{_axon_type_to_ts(output_type)}> {{")
    lines.append("    let current = input;")
    lines.append("    for (const stage of this._stages) {")
    lines.append("      current = await stage(current);")
    lines.append("    }")
    lines.append("    return current;")
    lines.append("  }")
    lines.append("}")
    return lines


def _runtime_helpers() -> list[str]:
    """Emit small AXON runtime helpers used by generated TS code."""
    return [
        "export function Ok<T>(value: T): Result<T, never> {",
        '  return { ok: true as const, value };',
        "}",
        "",
        "export function Err<E = Error>(error: E): Result<never, E> {",
        '  return { ok: false as const, error };',
        "}",
        "",
        "export async function act(toolName: string, args: Record<string, any>): Promise<any> {",
        '  throw new Error(`act("${toolName}") must be provided by the runtime`);',
        "}",
        "",
        "export async function think(message: string): Promise<void> {",
        '  console.log("[THINK]", message);',
        "}",
        "",
        "export async function observe(key: string, value: any): Promise<void> {",
        '  console.log("[OBSERVE]", key, value);',
        "}",
        "",
        "export async function store(key: string, value: any): Promise<void> {",
        '  console.log("[STORE]", key, value);',
        "}",
    ]


def _escape_ts_string(s: str) -> str:
    """Escape a string for TypeScript source insertion."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
