import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _subprocess_env() -> dict[str, str]:
    env = os.environ.copy()
    src = str(ROOT / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = src if not existing else f"{src}{os.pathsep}{existing}"
    return env

from axon.cli import build_file, build_to_stdout, main


SIMPLE_SOURCE = '''
tool Greet(name: Str) -> Str {
    /// Says hello.
    "Hello, {name}!"
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
'''


def test_build_file_writes_explicit_output(tmp_path):
    source = tmp_path / "hello.ax"
    output = tmp_path / "server.py"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    result = build_file(source, output_path=output)

    assert result == output
    code = output.read_text(encoding="utf-8")
    assert "Generated by AXON v0.1" in code
    assert "from fastmcp import FastMCP" in code
    assert "def greet(name: str) -> str:" in code


def test_build_file_uses_default_output_path(tmp_path):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    result = build_file(source)

    assert result == tmp_path / "hello_server.py"
    assert result.exists()


def test_build_to_stdout_returns_generated_code(tmp_path):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    code = build_to_stdout(source)

    assert "mcp = FastMCP(\"Bot\")" in code
    assert "AXON_AGENT_TOOLS" in code


def test_main_build_command(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    output = tmp_path / "server.py"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    exit_code = main(["build", str(source), "--output", str(output)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert output.exists()
    assert "Generated MCP server:" in captured.out


def test_main_build_stdout_command(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    exit_code = main(["build", str(source), "--stdout"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "Generated by AXON v0.1" in captured.out
    assert "def greet" in captured.out


def test_main_serve_dry_run_builds_but_does_not_run(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    output = tmp_path / "server.py"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    exit_code = main(["serve", str(source), "--output", str(output), "--dry-run"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert output.exists()
    assert "Dry run enabled" in captured.out


def test_main_missing_file_returns_error(capsys):
    exit_code = main(["build", "missing.ax"])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "source file not found" in captured.err


def test_main_syntax_error_returns_error(tmp_path, capsys):
    source = tmp_path / "bad.ax"
    source.write_text("agent Broken { tools: [] }", encoding="utf-8")

    exit_code = main(["build", str(source)])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "error:" in captured.err


def test_python_module_entrypoint_build(tmp_path):
    source = tmp_path / "hello.ax"
    output = tmp_path / "server.py"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "axon",
            "build",
            str(source),
            "--output",
            str(output),
        ],
        check=False,
        capture_output=True,
        text=True,
        cwd=ROOT,
        env=_subprocess_env(),
    )

    assert completed.returncode == 0
    assert output.exists()
    assert "Generated MCP server:" in completed.stdout


def test_main_validate_success(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    exit_code = main(["validate", str(source)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "passed AXON validation" in captured.out


def test_main_validate_reports_errors(tmp_path, capsys):
    source = tmp_path / "bad.ax"
    source.write_text('''
agent Broken {
    model: @anthropic/claude-4
    tools: [MissingTool]
    fn run(q: Str) -> Str { q }
}
''', encoding="utf-8")

    exit_code = main(["validate", str(source)])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "unknown tool" in captured.out
    assert "unknown-agent-tool" in captured.out


def test_main_validate_json_output(tmp_path, capsys):
    source = tmp_path / "bad.ax"
    source.write_text('''
agent Broken {
    model: @anthropic/claude-4
    tools: [MissingTool]
    fn run(q: Str) -> Str { q }
}
''', encoding="utf-8")

    exit_code = main(["validate", str(source), "--json"])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert '"code": "unknown-agent-tool"' in captured.out


def test_build_stops_on_validation_error(tmp_path, capsys):
    source = tmp_path / "bad.ax"
    source.write_text('''
agent Broken {
    model: @anthropic/claude-4
    tools: [MissingTool]
    fn run(q: Str) -> Str { q }
}
''', encoding="utf-8")

    exit_code = main(["build", str(source), "--stdout"])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "AXON validation failed" in captured.err


def test_main_smoke_success(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    exit_code = main(["smoke", str(source)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "passed AXON smoke test" in captured.out
    assert "tools: greet" in captured.out


def test_main_smoke_json_success(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")

    exit_code = main(["smoke", str(source), "--json"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"passed": true' in captured.out
    assert '"registered_tools"' in captured.out


def test_main_smoke_stops_on_validation_error(tmp_path, capsys):
    source = tmp_path / "bad.ax"
    source.write_text('''
agent Broken {
    model: @anthropic/claude-4
    tools: [MissingTool]
    fn run(q: Str) -> Str { q }
}
''', encoding="utf-8")

    exit_code = main(["smoke", str(source)])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "AXON validation failed" in captured.err


def test_main_config_show_redacts_secrets(tmp_path, capsys):
    config = tmp_path / "axon.toml"
    config.write_text('''
[defaults]
model = "@anthropic/claude-haiku"

[providers.anthropic]
api_key = "${ANTHROPIC_API_KEY}"

[providers.ollama]
base_url = "http://localhost:11434"
''', encoding="utf-8")

    exit_code = main(["config", "--config", str(config)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "Defaults:" in captured.out
    assert "model: @anthropic/claude-haiku" in captured.out
    assert "api_key: <redacted>" in captured.out
    assert "base_url: http://localhost:11434" in captured.out


def test_main_config_show_json_redacts_secrets(tmp_path, capsys):
    config = tmp_path / "axon.toml"
    config.write_text('''
[defaults]
model = "@anthropic/claude-haiku"

[providers.anthropic]
api_key = "${ANTHROPIC_API_KEY}"
''', encoding="utf-8")

    exit_code = main(["config", "--config", str(config), "--json"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"api_key": "<redacted>"' in captured.out
    assert "ANTHROPIC_API_KEY" not in captured.out


def test_main_config_missing_returns_error(capsys):
    exit_code = main(["config", "--config", "missing-axon.toml"])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "config file not found" in captured.err


def test_build_with_config_resolves_env_default_model(tmp_path):
    source = tmp_path / "hello.ax"
    config = tmp_path / "axon.toml"
    source.write_text('''
tool Greet(name: Str) -> Str {
    /// Says hello.
    "Hello"
}
agent Bot {
    model: env.DEFAULT_MODEL
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
''', encoding="utf-8")
    config.write_text('''
[defaults]
model = "@anthropic/claude-haiku"
''', encoding="utf-8")

    code = build_to_stdout(source, config_path=config)

    assert 'AXON_PROVIDER = os.getenv("AXON_PROVIDER", "anthropic")' in code
    assert 'AXON_MODEL    = os.getenv("AXON_MODEL",    "claude-haiku-20241022")' in code


def test_main_trace_preview_success(tmp_path, capsys):
    source = tmp_path / "trace.ax"
    source.write_text('''
tool Search(q: Str) -> Str {
    /// Searches.
    q
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Search]
    fn run(q: Str) -> Str {
        think "Plan"
        let result = act Search(q: q)?
        store memory.working["result"] = result
        result
    }
}
''', encoding="utf-8")

    exit_code = main(["trace-preview", str(source)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "AEL trace preview: 3 event" in captured.out
    assert "think [Bot.run]: Plan" in captured.out
    assert "act [Bot.run]: Search(q=q)" in captured.out


def test_main_trace_preview_jsonl_success(tmp_path, capsys):
    source = tmp_path / "trace.ax"
    source.write_text('''
tool Search(q: Str) -> Str { /// Searches. q }
agent Bot {
    model: @anthropic/claude-4
    tools: [Search]
    fn run(q: Str) -> Str {
        let result = act Search(q: q)?
        result
    }
}
''', encoding="utf-8")

    exit_code = main(["trace-preview", str(source), "--jsonl"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"t":"act"' in captured.out
    assert '"tool":"Search"' in captured.out


def test_main_trace_read_summary(tmp_path, capsys):
    trace = tmp_path / "trace.jsonl"
    trace.write_text(
        '{"t":"think","content":"Plan","agent":"Bot","ts":1}\n'
        '{"t":"act","tool":"Search","args":{"q":"axon"},"agent":"Bot","ts":2}\n'
        '{"t":"store","key":"working.result","value":"ok","agent":"Other","ts":3}\n',
        encoding="utf-8",
    )

    exit_code = main(["trace-read", str(trace)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "AEL trace log:" in captured.out
    assert "events: 3" in captured.out
    assert "by type: act=1, store=1, think=1" in captured.out
    assert "by agent: Bot=2, Other=1" in captured.out


def test_main_trace_read_events_and_filters(tmp_path, capsys):
    trace = tmp_path / "trace.jsonl"
    trace.write_text(
        '{"t":"think","content":"Plan","agent":"Bot"}\n'
        '{"t":"act","tool":"Search","args":{"q":"axon"},"agent":"Bot"}\n'
        '{"t":"act","tool":"OtherTool","args":{},"agent":"Other"}\n',
        encoding="utf-8",
    )

    exit_code = main(["trace-read", str(trace), "--type", "act", "--agent", "Bot", "--events"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "events: 1" in captured.out
    assert "act [Bot]: Search(q='axon')" in captured.out
    assert "OtherTool" not in captured.out


def test_main_trace_read_json_output(tmp_path, capsys):
    trace = tmp_path / "trace.jsonl"
    trace.write_text('{"t":"think","content":"Plan","agent":"Bot"}\n', encoding="utf-8")

    exit_code = main(["trace-read", str(trace), "--json"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"total_events": 1' in captured.out
    assert '"content": "Plan"' in captured.out


def test_main_trace_read_jsonl_output_with_filter(tmp_path, capsys):
    trace = tmp_path / "trace.jsonl"
    trace.write_text(
        '{"t":"think","content":"Plan","agent":"Bot"}\n'
        '{"t":"act","tool":"Search","args":{"q":"axon"},"agent":"Bot"}\n',
        encoding="utf-8",
    )

    exit_code = main(["trace-read", str(trace), "--type", "act", "--jsonl"])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"t":"act"' in captured.out
    assert '"tool":"Search"' in captured.out
    assert '"think"' not in captured.out


def test_main_trace_log_alias(tmp_path, capsys):
    trace = tmp_path / "trace.jsonl"
    trace.write_text('{"t":"think","content":"Plan"}\n', encoding="utf-8")

    exit_code = main(["trace-log", str(trace)])

    captured = capsys.readouterr()
    assert exit_code == 0
    assert "events: 1" in captured.out


def test_main_trace_read_bad_trace_returns_error(tmp_path, capsys):
    trace = tmp_path / "bad.jsonl"
    trace.write_text('{"t":"think","content":"Plan"}\nnot-json\n', encoding="utf-8")

    exit_code = main(["trace-read", str(trace)])

    captured = capsys.readouterr()
    assert exit_code == 1
    assert "line 2" in captured.err


def test_cli_syntax_ok(tmp_path, capsys):
    src = tmp_path / "ok.ax"
    src.write_text('tool T(x: Str) -> Str { /// D. x }', encoding="utf-8")
    exit_code = main(["syntax", str(src)])
    captured = capsys.readouterr()
    assert exit_code == 0
    assert "OK:" in captured.out


def test_cli_syntax_error_human(tmp_path, capsys):
    src = tmp_path / "bad.ax"
    src.write_text('tool T(x: Str) Str { /// D. x }', encoding="utf-8")
    exit_code = main(["syntax", str(src)])
    captured = capsys.readouterr()
    assert exit_code == 1
    assert "error:" in captured.out
    assert "Expected '->'" in captured.out
    assert "hint:" in captured.out
    assert "^" in captured.out


def test_cli_syntax_error_json(tmp_path, capsys):
    import json
    src = tmp_path / "bad.ax"
    src.write_text('agnt Bot { }', encoding="utf-8")
    exit_code = main(["syntax", str(src), "--json"])
    captured = capsys.readouterr()
    assert exit_code == 1
    payload = json.loads(captured.out)
    assert payload["ok"] is False
    assert payload["diagnostics"][0]["hint"] == "Did you mean `agent`?"


def test_version_command_prints_version(capsys):
    exit_code = main(["version"])
    captured = capsys.readouterr()
    assert exit_code == 0
    assert captured.out.strip() == "AXON 0.1.0"


def test_version_command_json(capsys):
    exit_code = main(["version", "--json"])
    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"version": "0.1.0"' in captured.out
    assert '"package_name": "axon-lang"' in captured.out


def test_info_command_prints_environment(capsys, tmp_path):
    (tmp_path / "axon.toml").write_text('[defaults]\nmodel = "@ollama/llama3"\n', encoding="utf-8")
    exit_code = main(["info", "--path", str(tmp_path)])
    captured = capsys.readouterr()
    assert exit_code == 0
    assert "AXON information" in captured.out
    assert "Version: 0.1.0" in captured.out
    assert "Config:" in captured.out
    assert "axon.toml" in captured.out


def test_info_command_json(capsys, tmp_path):
    exit_code = main(["info", "--path", str(tmp_path), "--json"])
    captured = capsys.readouterr()
    assert exit_code == 0
    assert '"version": "0.1.0"' in captured.out
    assert '"config_found": false' in captured.out


def test_health_command_prints_status(capsys):
    exit_code = main(["health"])
    captured = capsys.readouterr()
    assert exit_code in (0, 1)
    assert "AXON Health Check:" in captured.out
    assert "parser:" in captured.out
    assert "type_checker:" in captured.out


def test_health_command_json(capsys):
    exit_code = main(["health", "--json"])
    captured = capsys.readouterr()
    assert exit_code in (0, 1)
    import json
    data = json.loads(captured.out)
    assert "status" in data
    assert "checks" in data
    assert "parser" in data["checks"]


def test_run_stream_command(tmp_path, capsys):
    source = tmp_path / "hello.ax"
    source.write_text(SIMPLE_SOURCE, encoding="utf-8")
    exit_code = main(["run", str(source), "--stream"])
    captured = capsys.readouterr()
    assert exit_code == 0
    # Streaming may produce empty output with mock provider
    assert captured.out is not None


def test_run_sandbox_denied_tool(tmp_path, capsys):
    source = tmp_path / "sandbox.ax"
    source.write_text('''
tool Greet(name: Str) -> Str {
    "Hello, {name}!"
}

agent Bot {
    model: @mock/model
    tools: [Greet]
    fn run(q: Str) -> Str {
        act Greet(name: q)
    }
}
''', encoding="utf-8")
    exit_code = main(["run", str(source), "--arg", "q=World", "--sandbox-denied", "Greet"])
    captured = capsys.readouterr()
    assert exit_code == 1
    assert "denied" in captured.out.lower() or "sandbox" in captured.out.lower()


def test_run_uses_axon_toml_sandbox_defaults(tmp_path, capsys):
    toml = tmp_path / "axon.toml"
    toml.write_text('''
[sandbox]
timeout_ms = 100
max_depth = 5
denied_tools = "Greet"
''', encoding="utf-8")
    source = tmp_path / "hello.ax"
    source.write_text('''
tool Greet(name: Str) -> Str {
    "Hello, {name}!"
}

agent Bot {
    model: @mock/model
    tools: [Greet]
    fn run(q: Str) -> Str {
        act Greet(name: q)
    }
}
''', encoding="utf-8")
    exit_code = main(["run", str(source), "--arg", "q=World"])
    captured = capsys.readouterr()
    assert exit_code == 1
    assert "denied" in captured.out.lower()
