from axon.parser import parse
from axon.codegen.mcp import generate_mcp_server, type_to_python, to_snake_case


def test_snake_case():
    assert to_snake_case("FetchIssues") == "fetch_issues"
    assert to_snake_case("WebSearch") == "web_search"
    assert to_snake_case("AddLabel") == "add_label"
    assert to_snake_case("readCSV") == "read_csv"
    assert to_snake_case("HTTPClient") == "http_client"


def test_type_to_python_primitives():
    assert type_to_python("Str") == "str"
    assert type_to_python("Int") == "int"
    assert type_to_python("Float") == "float"
    assert type_to_python("Bool") == "bool"
    assert type_to_python("Any") == "Any"
    assert type_to_python("()") == "None"


def test_type_to_python_generics():
    assert type_to_python("List<Str>") == "list[str]"
    assert type_to_python("Option<Int>") == "Optional[int]"
    assert type_to_python("Map<Str, Int>") == "dict[str, int]"


def test_type_to_python_nested_generics():
    assert type_to_python("List<Option<Str>>") == "list[Optional[str]]"
    assert type_to_python("Map<Str, List<Int>>") == "dict[str, list[int]]"
    assert type_to_python("Stream<Str>") == "Iterator[str]"


def test_type_to_python_result():
    assert type_to_python("Result<List<Any>, ToolError>") == "dict"
    assert type_to_python("Result<Str, AgentError>") == "dict"


def test_type_to_python_literal_union():
    assert type_to_python('"low" | "medium" | "high"') == "str"


def test_generate_produces_fastmcp_import():
    source = '''
tool Greet(name: Str) -> Str {
    /// Says hello to someone.
    "Hello, {name}!"
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Result<Str, AgentError> { Ok(q) }
}
'''
    code = generate_mcp_server(parse(source))
    assert "from fastmcp import FastMCP" in code
    assert 'mcp = FastMCP(' in code


def test_generate_tool_function():
    source = '''
tool Greet(name: Str) -> Str {
    /// Says hello.
    "Hello!"
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "@mcp.tool()" in code
    assert "def greet(name: str) -> str:" in code
    assert "Says hello." in code
    assert "NotImplementedError" in code


def test_generate_int_param():
    source = '''
tool Paginate(page: Int, size: Int = 10) -> List<Any> {
    /// Paginates results.
    fetch(page, size)
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Paginate]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "def paginate(page: int, size: int = 10)" in code


def test_generate_header_comment():
    source = '''
tool T(x: Str) -> Str { /// D. x }
agent A {
    model: @anthropic/claude-4
    tools: [T]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "Generated by AXON v0.1" in code


def test_generate_agent_metadata():
    source = '''
tool T(x: Str) -> Str { /// D. x }
agent MyAgent {
    model: @anthropic/claude-4
    tools: [T]
    memory: Memory<Semantic>
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert 'AXON_AGENT_TOOLS' in code
    assert '"T"' in code
    assert 'AXON_AGENT_MEMORY' in code
    assert '"Semantic"' in code


def test_generate_axon_body_comment():
    source = '''
tool Fetch(url: Str) -> Str {
    /// Gets a URL.
    http.get(url)
}
agent A {
    model: @anthropic/claude-4
    tools: [Fetch]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "# AXON body:" in code
    assert "http.get(url)" in code


def test_generate_schedule_metadata():
    source = '''
tool FetchMetrics(endpoint: Str) -> Result<Any, ToolError> {
    /// Fetches metrics.
    http.get(endpoint)
}
agent MonitorAgent {
    model: @anthropic/claude-haiku
    tools: [FetchMetrics]
    memory: Memory<ShortTerm>(capacity: 500)

    @schedule(every: 5.minutes)
    fn watch(endpoint: Str) -> Result<(), AgentError> { Ok(()) }
}
'''
    code = generate_mcp_server(parse(source))
    assert 'AXON_AGENT_SCHEDULE = "every: 5.minutes"' in code
    assert 'AXON_AGENT_MEMORY_OPTIONS = {"capacity": "500"}' in code


def test_generated_code_compiles_without_fastmcp_installed():
    source = '''
tool Greet(name: Str, excited: Bool = true) -> Str {
    /// Says hello.
    "Hello"
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    compile(code, "generated_axon_server.py", "exec")
    assert "excited: bool = True" in code


def test_generate_ignores_type_alias_declarations():
    source = '''
type UserName = Str

tool Greet(name: UserName) -> Str {
    /// Says hello.
    "Hello!"
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: UserName) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "def greet(name: Any) -> str:" in code
    assert "type UserName" not in code
    assert "Generated by AXON v0.1" in code


def test_generate_ignores_prompt_declarations():
    source = '''
prompt GreetPrompt(name: Str, @budget(tokens: 100)) -> Str {
    """
    Write a greeting for {name}.
    """
}

tool Greet(name: Str) -> Str {
    /// Says hello.
    "Hello!"
}

agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "def greet(name: str) -> str:" in code
    assert "GreetPrompt" not in code


def test_generate_ignores_flow_declarations():
    source = '''
flow AnswerFlow(question: Str) -> Str {
    stage Retrieve(query: Str) -> List<Chunk>
    stage Answer(chunks: List<Chunk>, question: Str) -> Str
    Retrieve -> Answer
}

tool Respond(text: Str) -> Str {
    /// Responds with text.
    text
}

agent Bot {
    model: @anthropic/claude-4
    tools: [Respond]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source))
    assert "def respond(text: str) -> str:" in code
    assert "AnswerFlow" not in code
    assert "stage Retrieve" not in code


def test_generate_with_parsed_body_emits_python():
    source = '''
tool Greet(name: Str) -> Str {
    /// Says hello to someone.
    "Hello, {name}!"
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source, parse_expressions=True))
    assert "NotImplementedError" not in code
    assert 'f"Hello, {name}!"' in code


def test_generate_with_act_translation():
    source = '''
tool Search(query: Str) -> List<Any> {
    /// Searches the web.
    act WebSearch(query: query, max_results: 5)?
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Search]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source, parse_expressions=True))
    assert "NotImplementedError" not in code
    assert "web_search(query=query, max_results=5)" in code


def test_generate_multi_line_let_block():
    source = '''
tool Greet(name: Str) -> Str {
    let msg = "Hello, " + name + "!"
    msg
}
agent Bot {
    model: @anthropic/claude-4
    tools: [Greet]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source, parse_expressions=True))
    assert "NotImplementedError" not in code
    assert "msg = " in code
    assert "return msg" in code


def test_generate_multi_line_with_act():
    source = '''
tool FetchAndProcess(url: Str) -> Str {
    let raw = act HttpGet(url: url)?
    raw
}
agent Bot {
    model: @anthropic/claude-4
    tools: [FetchAndProcess]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source, parse_expressions=True))
    assert "NotImplementedError" not in code
    assert "raw = http_get" in code
    assert "return raw" in code


def test_generate_for_loop():
    source = '''
tool SumItems(items: List<Int>) -> Int {
    let total = 0
    for item in items {
        total = total + item
    }
    total
}
agent Bot {
    model: @anthropic/claude-4
    tools: [SumItems]
    fn run(q: Str) -> Str { q }
}
'''
    code = generate_mcp_server(parse(source, parse_expressions=True))
    assert "NotImplementedError" not in code
    assert "for item in items:" in code
    assert "total = (total + item)" in code
    assert "return total" in code
