from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys

from axon.precommit import (
    PrecommitError,
    check_precommit_hook,
    render_precommit_hook,
    run_precommit_checks,
    write_precommit_hook,
)


ROOT = Path(__file__).resolve().parents[1]


def _env() -> dict[str, str]:
    env = os.environ.copy()
    src_path = str(ROOT / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = src_path if not existing else f"{src_path}{os.pathsep}{existing}"
    return env


def test_render_precommit_hook_delegates_to_axon_precommit_run():
    hook = render_precommit_hook()
    assert hook.startswith("#!/usr/bin/env sh")
    assert "Generated by AXON v0.1" in hook
    assert "python" in hook
    assert "-m axon precommit run" in hook
    assert "AXON_PYTHON" in hook


def test_write_and_check_precommit_hook(tmp_path: Path):
    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    hook_path = hooks_dir / "pre-commit"

    result = write_precommit_hook(tmp_path, hook_path=hook_path)
    assert result.installed is True
    assert hook_path.exists()
    assert os.access(hook_path, os.X_OK)
    assert hook_path.read_text(encoding="utf-8") == render_precommit_hook()

    check = check_precommit_hook(tmp_path, hook_path=hook_path)
    assert check.installed is True


def test_write_precommit_hook_preserves_existing_without_force(tmp_path: Path):
    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    hook_path = hooks_dir / "pre-commit"
    hook_path.write_text("custom hook", encoding="utf-8")

    try:
        write_precommit_hook(tmp_path, hook_path=hook_path)
    except PrecommitError as exc:
        assert "already exists" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected PrecommitError")

    result = write_precommit_hook(tmp_path, hook_path=hook_path, force=True)
    assert result.installed is True
    assert hook_path.read_text(encoding="utf-8") == render_precommit_hook()


def test_check_precommit_hook_reports_missing(tmp_path: Path):
    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    result = check_precommit_hook(tmp_path, hook_path=hooks_dir / "pre-commit")
    assert result.installed is False
    assert "not installed" in result.message


def test_run_precommit_checks_on_current_project_passes_fast_path():
    result = run_precommit_checks(ROOT, full=False, include_pytest=False)
    assert result.passed is True
    names = [check.name for check in result.checks]
    assert "compile" in names
    assert "dependency audit" in names
    assert "repository hygiene" in names
    assert "project quality gate" in names
    assert "formatter idempotency" in names
    assert "pytest" not in names


def test_precommit_cli_print_and_check_json(tmp_path: Path):
    completed = subprocess.run(
        [sys.executable, "-m", "axon", "precommit", "print"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        env=_env(),
    )
    assert completed.returncode == 0
    assert "-m axon precommit run" in completed.stdout

    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    hook_path = hooks_dir / "pre-commit"
    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "axon",
            "precommit",
            "install",
            "--path",
            str(tmp_path),
            "--hook-path",
            str(hook_path),
            "--json",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        env=_env(),
    )
    assert completed.returncode == 0, completed.stderr
    payload = json.loads(completed.stdout)
    assert payload["installed"] is True

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "axon",
            "precommit",
            "check",
            "--path",
            str(tmp_path),
            "--hook-path",
            str(hook_path),
            "--json",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        env=_env(),
    )
    assert completed.returncode == 0
    payload = json.loads(completed.stdout)
    assert payload["installed"] is True


def test_precommit_docs_and_template_are_present():
    assert (ROOT / "docs" / "PRECOMMIT.md").exists()
    assert (ROOT / ".githooks" / "pre-commit").exists()
    assert (ROOT / ".githooks" / "pre-commit").read_text(encoding="utf-8") == render_precommit_hook()
