//! Code generator — generates Go, Rust, TypeScript, and MCP server code from AXON IR.

use crate::{AxonIR, ToolDef, AgentDef, TypeAliasDef};

pub fn generate(ir: &AxonIR, target: &str) -> String {
    match target {
        "go" => gen_go(ir),
        "rust" => gen_rust(ir),
        "typescript" | "ts" => gen_ts(ir),
        "mcp" => gen_mcp(ir),
        _ => format!("// Unknown target: {}", target),
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn parse_generic(t: &str) -> Option<(String, Vec<String>)> {
    let lt = t.find('<')?;
    let name = t[..lt].trim().to_string();
    let gt = t.rfind('>')?;
    let inner = &t[lt + 1..gt];
    let mut args = Vec::new();
    let mut depth = 0;
    let mut cur = String::new();
    for ch in inner.chars() {
        match ch {
            '<' => { depth += 1; cur.push(ch); }
            '>' => { depth -= 1; cur.push(ch); }
            ',' if depth == 0 => { args.push(cur.trim().to_string()); cur.clear(); }
            _ => cur.push(ch),
        }
    }
    if !cur.trim().is_empty() { args.push(cur.trim().to_string()); }
    Some((name, args))
}

fn to_exported(name: &str) -> String {
    let parts: Vec<&str> = name.split(|c: char| c == '_' || c == '-' || c.is_whitespace()).collect();
    parts.iter().map(|p| {
        let mut c = p.chars();
        match c.next() { Some(f) => f.to_uppercase().collect::<String>() + c.as_str(), None => String::new() }
    }).collect()
}

fn escape_str(s: &str) -> String { s.replace('\\', "\\\\").replace('"', "\\\"") }

fn axon_to_go(t: &str) -> String {
    let t = t.trim();
    match t {
        "Str" => "string", "Int" => "int64", "Float" => "float64",
        "Bool" => "bool", "Any" => "any", "Bytes" => "[]byte", "" => "any",
        _ => return if let Some((n, a)) = parse_generic(t) {
            match n.as_str() {
                "List" if a.len()==1 => format!("[]{}", axon_to_go(&a[0])),
                "Set" if a.len()==1 => format!("map[{}]struct{{}}", axon_to_go(&a[0])),
                "Map" if a.len()==2 => format!("map[{}]{}", axon_to_go(&a[0]), axon_to_go(&a[1])),
                "Option" if a.len()==1 => format!("*{}", axon_to_go(&a[0])),
                "Result" if a.len()>=1 => format!("Result[{}, {}]", axon_to_go(&a[0]), if a.len()>1 { axon_to_go(&a[1]) } else { "error".into() }),
                _ => t.into(),
            }
        } else if t.contains('|') && t.contains('"') { "string".into() } else { t.into() },
    }.into()
}

fn axon_to_rust(t: &str) -> String {
    let t = t.trim();
    match t {
        "Str" => "String", "Int" => "i64", "Float" => "f64",
        "Bool" => "bool", "Any" => "serde_json::Value", "Bytes" => "Vec<u8>", "" => "serde_json::Value",
        _ => return if let Some((n, a)) = parse_generic(t) {
            match n.as_str() {
                "List" if a.len()==1 => format!("Vec<{}>", axon_to_rust(&a[0])),
                "Set" if a.len()==1 => format!("std::collections::HashSet<{}>", axon_to_rust(&a[0])),
                "Map" if a.len()==2 => format!("HashMap<{}, {}>", axon_to_rust(&a[0]), axon_to_rust(&a[1])),
                "Option" if a.len()==1 => format!("Option<{}>", axon_to_rust(&a[0])),
                "Result" if a.len()>=1 => format!("Result<{}, {}>", axon_to_rust(&a[0]), if a.len()>1 { axon_to_rust(&a[1]) } else { "String".into() }),
                _ => t.into(),
            }
        } else { t.into() },
    }.into()
}

fn axon_to_ts(t: &str) -> String {
    let t = t.trim();
    match t {
        "Str" => "string", "Int" => "number", "Float" => "number",
        "Bool" => "boolean", "Any" => "any", "Bytes" => "Uint8Array", "" => "any",
        _ => return if let Some((n, a)) = parse_generic(t) {
            match n.as_str() {
                "List" if a.len()==1 => format!("{}[]", axon_to_ts(&a[0])),
                "Set" if a.len()==1 => format!("Set<{}>", axon_to_ts(&a[0])),
                "Map" if a.len()==2 => format!("Map<{}, {}>", axon_to_ts(&a[0]), axon_to_ts(&a[1])),
                "Option" if a.len()==1 => format!("{} | null", axon_to_ts(&a[0])),
                "Result" if a.len()>=1 => format!("Result<{}{}>", axon_to_ts(&a[0]), if a.len()>1 { format!(", {}", axon_to_ts(&a[1])) } else { String::new() }),
                _ => t.into(),
            }
        } else if t.contains('|') { t.into() } else { t.into() },
    }.into()
}

// ── Go ───────────────────────────────────────────────────────────────────────

fn gen_go(ir: &AxonIR) -> String {
    let mut l: Vec<String> = vec![
        "// Code generated by AXON Go target. DO NOT EDIT.".into(),
        "package axon_app".into(), "".into(),
        "import (".into(), "\t\"context\"".into(), "\t\"fmt\"".into(), ")".into(), "".into(),
        "type Result[T any, E any] struct { Ok T; Err E; IsErr bool }".into(),
        "func _zero[T any]() T { var z T; return z }".into(), "".into(),
    ];
    for ta in &ir.type_aliases { l.extend(go_type_alias(ta)); l.push("".into()); }
    for tool in &ir.tools { l.extend(go_tool(tool)); l.push("".into()); }
    for agent in &ir.agents { l.extend(go_agent(agent)); l.push("".into()); }
    l.join("\n")
}

fn go_type_alias(ta: &TypeAliasDef) -> Vec<String> {
    if !ta.fields.is_empty() {
        let mut l = vec![format!("type {} struct {{", ta.name)];
        for f in &ta.fields { l.push(format!("\t{} {} `json:\"{}\"`", to_exported(&f.name), axon_to_go(&f.type_str), f.name)); }
        l.push("}".into()); l
    } else { vec![format!("type {} = {}", ta.name, axon_to_go(&ta.value))] }
}

fn go_tool(tool: &ToolDef) -> Vec<String> {
    let p: Vec<String> = tool.params.iter().map(|p| format!("{} {}", p.name, axon_to_go(&p.type_str))).collect();
    let r = axon_to_go(&tool.return_type);
    let mut l = Vec::new();
    if !tool.docstrings.is_empty() { l.push(format!("// {}", tool.docstrings[0])); }
    l.push(format!("func {}(ctx context.Context, {}) ({}, error) {{", to_exported(&tool.name), p.join(", "), r));
    l.push(format!("\treturn _zero[{}](), fmt.Errorf(\"not implemented\")", r));
    l.push("}".into()); l
}

fn go_agent(a: &AgentDef) -> Vec<String> {
    let mut l = vec![
        format!("type {} struct {{ Model string; Tools []string; Version string }}", a.name),
        format!("func New{}() *{} {{ return &{}{{Model:\"{}\", Tools:[]string{{}}, Version:\"{}\"}} }}", a.name, a.name, a.name, escape_str(&a.model), escape_str(&a.version)),
    ];
    for m in &a.methods {
        let p: Vec<String> = m.params.iter().map(|p| format!("{} {}", p.name, axon_to_go(&p.type_str))).collect();
        let r = axon_to_go(&m.return_type);
        l.push(format!("func (a *{}) {}(ctx context.Context, {}) ({}, error) {{ return _zero[{}](), fmt.Errorf(\"not implemented\") }}", a.name, to_exported(&m.name), p.join(", "), r, r));
    }
    l
}

// ── Rust ──────────────────────────────────────────────────────────────────────

fn gen_rust(ir: &AxonIR) -> String {
    let mut l: Vec<String> = vec![
        "// Code generated by AXON Rust target. DO NOT EDIT.".into(), "".into(),
        "use std::collections::HashMap;".into(), "".into(),
    ];
    for ta in &ir.type_aliases { l.extend(rust_type_alias(ta)); l.push("".into()); }
    for tool in &ir.tools { l.extend(rust_tool(tool)); l.push("".into()); }
    for agent in &ir.agents { l.extend(rust_agent(agent)); l.push("".into()); }
    l.join("\n")
}

fn rust_type_alias(ta: &TypeAliasDef) -> Vec<String> {
    if !ta.fields.is_empty() {
        let mut l = vec!["#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]".into(), format!("pub struct {} {{", ta.name)];
        for f in &ta.fields { l.push(format!("\tpub {}: {},", f.name, axon_to_rust(&f.type_str))); }
        l.push("}".into()); l
    } else { vec![format!("pub type {} = {};", ta.name, axon_to_rust(&ta.value))] }
}

fn rust_tool(tool: &ToolDef) -> Vec<String> {
    let p: Vec<String> = tool.params.iter().map(|p| format!("{}: {}", p.name, axon_to_rust(&p.type_str))).collect();
    let r = axon_to_rust(&tool.return_type);
    let mut l = Vec::new();
    if !tool.docstrings.is_empty() { l.push(format!("/// {}", tool.docstrings[0])); }
    l.push(format!("pub fn {}({}) -> Result<{}, String> {{", tool.name, p.join(", "), r));
    l.push(format!("\tErr(\"not implemented\".into())"));
    l.push("}".into()); l
}

fn rust_agent(a: &AgentDef) -> Vec<String> {
    let mut l = vec![
        format!("pub struct {} {{ pub model: String, pub tools: Vec<String>, pub version: String }}", a.name),
        format!("impl {} {{ pub fn new() -> Self {{ Self {{ model: \"{}\".into(), tools: vec![], version: \"{}\".into() }} }}", a.name, escape_str(&a.model), escape_str(&a.version)),
    ];
    for m in &a.methods {
        let p: Vec<String> = m.params.iter().map(|p| format!("{}: {}", p.name, axon_to_rust(&p.type_str))).collect();
        let r = axon_to_rust(&m.return_type);
        l.push(format!("\tpub fn {}(&self, {}) -> Result<{}, String> {{ Err(\"not implemented\".into()) }}", m.name, p.join(", "), r));
    }
    l.push("}".into()); l
}

// ── TypeScript ────────────────────────────────────────────────────────────────

fn gen_ts(ir: &AxonIR) -> String {
    let mut l: Vec<String> = vec![
        "// Generated by AXON TypeScript target".into(), "".into(),
        "export type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E };".into(),
        "export type Option<T> = T | null;".into(), "".into(),
    ];
    if !ir.type_aliases.is_empty() {
        l.push("// ── Types ──".into()); l.push("".into());
        for ta in &ir.type_aliases { l.extend(ts_type_alias(ta)); l.push("".into()); }
    }
    if !ir.tools.is_empty() {
        l.push("// ── Tools ──".into()); l.push("".into());
        for tool in &ir.tools { l.extend(ts_tool(tool)); l.push("".into()); }
    }
    if !ir.agents.is_empty() {
        l.push("// ── Agents ──".into()); l.push("".into());
        for agent in &ir.agents { l.extend(ts_agent(agent)); l.push("".into()); }
    }
    l.join("\n")
}

fn ts_type_alias(ta: &TypeAliasDef) -> Vec<String> {
    if !ta.fields.is_empty() {
        let mut l = vec![format!("export interface {} {{", ta.name)];
        for f in &ta.fields { l.push(format!("  {}: {};", f.name, axon_to_ts(&f.type_str))); }
        l.push("}".into()); l
    } else { vec![format!("export type {} = {};", ta.name, axon_to_ts(&ta.value))] }
}

fn ts_tool(tool: &ToolDef) -> Vec<String> {
    let p: Vec<String> = tool.params.iter().map(|p| format!("{}: {}", p.name, axon_to_ts(&p.type_str))).collect();
    let r = axon_to_ts(&tool.return_type);
    let mut l = Vec::new();
    if !tool.docstrings.is_empty() { l.push(format!("/** {} */", tool.docstrings[0])); }
    l.push(format!("export async function {}({}): Promise<Result<{}>> {{", tool.name, p.join(", "), r));
    l.push(format!("\t// TODO: implement {}", tool.name));
    l.push("\treturn { ok: false, error: new Error(\"not implemented\") };".into());
    l.push("}".into()); l
}

fn ts_agent(a: &AgentDef) -> Vec<String> {
    let mut l = vec![format!("export class {} {{", a.name)];
    l.push(format!("  model = \"{}\";", escape_str(&a.model)));
    l.push(format!("  tools: string[] = [];"));
    l.push(format!("  version = \"{}\";", escape_str(&a.version)));
    for m in &a.methods {
        let p: Vec<String> = m.params.iter().map(|p| format!("{}: {}", p.name, axon_to_ts(&p.type_str))).collect();
        let r = axon_to_ts(&m.return_type);
        l.push(format!("  async {}({}): Promise<Result<{}>> {{ return {{ ok: false, error: new Error(\"not implemented\") }}; }}", m.name, p.join(", "), r));
    }
    l.push("}".into()); l
}

// ── MCP ───────────────────────────────────────────────────────────────────────

fn gen_mcp(ir: &AxonIR) -> String {
    let agent = ir.agents.first();
    let model = agent.map(|a| a.model.as_str()).unwrap_or("@mock/gpt");
    let agent_name = agent.map(|a| a.name.as_str()).unwrap_or("Agent");
    let header = format!("\"\"\"\nGenerated by AXON v0.1\nAgent: {}\nModel: {}\nDO NOT EDIT \u{2014} regenerate with: axon build <source.ax>\n\"\"\"", agent_name, model);
    let mut l: Vec<String> = vec![
        header, "".into(),
        "from fastmcp import FastMCP".into(),
        "from typing import Any, Optional".into(),
        "import os".into(), "".into(),
        format!("mcp = FastMCP(\"{}\")", agent_name), "".into(),
    ];
    for tool in &ir.tools {
        let p: Vec<String> = tool.params.iter().map(|p| format!("{}: str", p.name)).collect();
        if !tool.docstrings.is_empty() { l.push(format!("# {}", tool.docstrings[0])); }
        l.push("@mcp.tool()".into());
        l.push(format!("def {}({}) -> str:", tool.name, p.join(", ")));
        let doc = if !tool.docstrings.is_empty() { &tool.docstrings[0] } else { &tool.name };
        l.push(format!("    \"\"\"{}\"\"\"", doc));
        l.push("    # TODO: implement".into());
        l.push("    return \"not implemented\"".into());
        l.push("".into());
    }
    l.push("if __name__ == \"__main__\":".into());
    l.push("    mcp.run()".into());
    l.join("\n")
}
