"""AXON Phase 1 prototype package."""

from axon.ast_nodes import (
    AgentDecl,
    FlowDecl,
    Annotation,
    ImportDecl,
    MemoryDecl,
    MethodDecl,
    Param,
    PromptDecl,
    RagDecl,
    StageDecl,
    ToolDecl,
    TypeAliasDecl,
)
from axon.parser import parse
from axon.ast_snapshot import (
    SnapshotCheckResult,
    check_snapshot_file,
    declaration_to_dict,
    declarations_to_dicts,
    declarations_to_json,
    source_file_to_snapshot_json,
    source_to_snapshot_json,
    write_snapshot_file,
)
from axon.config import AxonConfig, ConfigError, ProviderConfig, find_config_path, load_config, parse_model_ref
from axon.contributor import TaskTicket, build_task_ticket, format_task_ticket, task_ticket_to_json, write_task_ticket
from axon.info import AxonInfo, collect_info, format_info, format_version, get_version, info_to_json, version_to_json
from axon.dependency_audit import DependencyAuditReport, DependencyFinding, audit_dependencies, dependency_audit_to_json, format_dependency_audit
from axon.project import ProjectInitError, ProjectInitResult, create_project, init_project
from axon.release_notes import ReleaseNotes, build_release_notes, format_release_notes, release_notes_to_json, write_release_notes

from axon.format_snapshot import (
    FormatSnapshotCheckResult,
    check_format_snapshot_file,
    source_file_to_formatted_snapshot,
    write_format_snapshot_file,
)
from axon.syntax import (
    SyntaxCheckResult,
    SyntaxDiagnostic,
    check_syntax,
    check_syntax_file,
    diagnostic_from_syntax_error,
    diagnostics_to_json as syntax_diagnostics_to_json,
    result_to_json as syntax_result_to_json,
)

from axon.trace_extract import (
    TraceExtractionOptions,
    extract_trace_events_from_body,
    extract_trace_events_from_method,
    extract_trace_preview,
    extract_trace_preview_from_file,
    extract_trace_preview_from_source,
    format_trace_preview,
    trace_preview_to_json,
)
from axon.trace import (
    ActEvent,
    AELTraceEvent,
    ObserveEvent,
    StoreEvent,
    ThinkEvent,
    TraceFormatError,
    TraceLog,
    TraceRecorder,
    event_from_dict,
)

from axon.trace_reader import (
    TraceSummary,
    filter_trace_log,
    format_trace_summary,
    read_trace_file,
    summarize_trace_log,
    trace_events_to_dicts,
    trace_report_to_json,
)

from axon.type_checker import (
    Type,
    TypeKind,
    PrimitiveType,
    GenericType,
    RecordType,
    UnionType,
    FunctionType,
    parse_type,
    types_equal,
    is_subtype,
    TypeChecker,
    check_types,
)

from axon.token_budget import (
    TokenBudget,
    estimate_tokens,
    estimate_prompt_budget,
    validate_prompt_budgets,
    TokenBudgetEstimator,
    check_token_budgets,
)

from axon.expression_ast import (
    BinaryOpExpr,
    BlockExpr,
    CallExpr,
    ErrorExpr,
    Expr,
    IfExpr,
    IndexExpr,
    LetExpr,
    LiteralExpr,
    ListExpr,
    MapExpr,
    MatchArm,
    MatchExpr,
    MemberAccessExpr,
    NoneExpr,
    OkExpr,
    PoolExpr,
    ReceiveExpr,
    ReturnExpr,
    SendExpr,
    BroadcastExpr,
    DiscoverExpr,
    SpawnExpr,
    PauseExpr,
    ResumeExpr,
    TerminateExpr,
    ParExpr,
    StructuredOutputExpr,
    SomeExpr,
    StringInterpolationExpr,
    UnaryOpExpr,
    VariableExpr,
)
from axon.expression_parser import ExpressionParser, parse_expression
from axon.lsp_server import (
    AxonLanguageServer,
    run_lsp_server,
)

__version__ = "0.1.0"

__all__ = [
    "AgentDecl",
    "FlowDecl",
    "Annotation",
    "ImportDecl",
    "MemoryDecl",
    "MethodDecl",
    "Param",
    "PromptDecl",
    "RagDecl",
    "StageDecl",
    "ToolDecl",
    "TypeAliasDecl",
    "parse",
    "SnapshotCheckResult",
    "check_snapshot_file",
    "declaration_to_dict",
    "declarations_to_dicts",
    "declarations_to_json",
    "source_file_to_snapshot_json",
    "source_to_snapshot_json",
    "write_snapshot_file",
    "TaskTicket",
    "build_task_ticket",
    "format_task_ticket",
    "task_ticket_to_json",
    "write_task_ticket",
    "AxonConfig",
    "ConfigError",
    "ProviderConfig",
    "find_config_path",
    "load_config",
    "parse_model_ref",
    "DependencyAuditReport",
    "DependencyFinding",
    "audit_dependencies",
    "dependency_audit_to_json",
    "format_dependency_audit",
    "AxonInfo",
    "collect_info",
    "format_info",
    "format_version",
    "get_version",
    "info_to_json",
    "version_to_json",
    "ProjectInitError",
    "ProjectInitResult",
    "create_project",
    "init_project",
    "ReleaseNotes",
    "build_release_notes",
    "format_release_notes",
    "release_notes_to_json",
    "write_release_notes",
    "write_format_snapshot_file",
    "source_file_to_formatted_snapshot",
    "check_format_snapshot_file",
    "FormatSnapshotCheckResult",
    "ActEvent",
    "AELTraceEvent",
    "ObserveEvent",
    "StoreEvent",
    "ThinkEvent",
    "TraceFormatError",
    "TraceLog",
    "TraceRecorder",
    "TraceExtractionOptions",
    "extract_trace_events_from_body",
    "extract_trace_events_from_method",
    "extract_trace_preview",
    "extract_trace_preview_from_file",
    "extract_trace_preview_from_source",
    "format_trace_preview",
    "trace_preview_to_json",
    "event_from_dict",
    "trace_report_to_json",
    "trace_events_to_dicts",
    "summarize_trace_log",
    "read_trace_file",
    "format_trace_summary",
    "filter_trace_log",
    "TraceSummary",
    "SyntaxCheckResult",
    "SyntaxDiagnostic",
    "check_syntax",
    "check_syntax_file",
    "diagnostic_from_syntax_error",
    "syntax_diagnostics_to_json",
    "syntax_result_to_json",
    "Type",
    "TypeKind",
    "PrimitiveType",
    "GenericType",
    "RecordType",
    "UnionType",
    "FunctionType",
    "parse_type",
    "types_equal",
    "is_subtype",
    "TypeChecker",
    "check_types",
    "TokenBudget",
    "estimate_tokens",
    "estimate_prompt_budget",
    "validate_prompt_budgets",
    "TokenBudgetEstimator",
    "check_token_budgets",
    # Expression AST
    "BinaryOpExpr",
    "BlockExpr",
    "CallExpr",
    "ErrorExpr",
    "Expr",
    "IfExpr",
    "IndexExpr",
    "LetExpr",
    "LiteralExpr",
    "ListExpr",
    "MapExpr",
    "MatchArm",
    "MatchExpr",
    "MemberAccessExpr",
    "NoneExpr",
    "OkExpr",
    "PoolExpr",
    "ReceiveExpr",
    "ReturnExpr",
    "SendExpr",
    "BroadcastExpr",
    "DiscoverExpr",
    "SpawnExpr",
    "PauseExpr",
    "ResumeExpr",
    "TerminateExpr",
    "ParExpr",
    "StructuredOutputExpr",
    "SomeExpr",
    "StringInterpolationExpr",
    "UnaryOpExpr",
    "VariableExpr",
    # Expression parser
    "ExpressionParser",
    "parse_expression",
    # LSP server
    "AxonLanguageServer",
    "run_lsp_server",
]
