"""Pre-commit hook template and local quality-gate runner for AXON projects.

This module intentionally uses only the Python standard library and existing
AXON CLI entry points. It installs a small Git hook that delegates back to
``python -m axon precommit run`` so the hook remains stable while the Python
quality-gate implementation evolves.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import os
from pathlib import Path
import stat
import subprocess
import sys
import tempfile
from typing import Sequence


class PrecommitError(Exception):
    """Raised for user-facing pre-commit hook failures."""


HOOK_TEMPLATE = """#!/usr/bin/env sh
# Generated by AXON v0.1
# Local quality gate for AXON projects. Do not edit by hand unless intentional.
set -eu

PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$PROJECT_ROOT"

PYTHON_BIN="${AXON_PYTHON:-python}"
exec "$PYTHON_BIN" -m axon precommit run --path "$PROJECT_ROOT"
"""


@dataclass(frozen=True)
class PrecommitInstallResult:
    """Result of installing or checking an AXON Git pre-commit hook."""

    path: Path
    installed: bool
    message: str

    def to_dict(self) -> dict[str, object]:
        return {
            "path": str(self.path),
            "installed": self.installed,
            "message": self.message,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)


@dataclass(frozen=True)
class PrecommitCheckResult:
    """One local pre-commit check result."""

    name: str
    command: list[str]
    returncode: int
    stdout: str = ""
    stderr: str = ""

    @property
    def passed(self) -> bool:
        return self.returncode == 0

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "command": self.command,
            "returncode": self.returncode,
            "passed": self.passed,
            "stdout": self.stdout,
            "stderr": self.stderr,
        }


@dataclass(frozen=True)
class PrecommitRunResult:
    """Aggregate result of running local pre-commit quality checks."""

    project_path: Path
    checks: list[PrecommitCheckResult] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return all(check.passed for check in self.checks)

    def to_dict(self) -> dict[str, object]:
        return {
            "project_path": str(self.project_path),
            "passed": self.passed,
            "checks": [check.to_dict() for check in self.checks],
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    def format(self) -> str:
        lines = [f"AXON pre-commit checks: {'PASS' if self.passed else 'FAIL'}", f"Project: {self.project_path}"]
        for check in self.checks:
            marker = "✓" if check.passed else "✗"
            command = " ".join(check.command)
            lines.append(f"{marker} {check.name}: {command}")
            if not check.passed:
                if check.stdout.strip():
                    lines.append("  stdout:")
                    lines.extend(f"    {line}" for line in check.stdout.strip().splitlines())
                if check.stderr.strip():
                    lines.append("  stderr:")
                    lines.extend(f"    {line}" for line in check.stderr.strip().splitlines())
        return "\n".join(lines)


def render_precommit_hook() -> str:
    """Return the shell pre-commit hook template."""
    return HOOK_TEMPLATE


def default_hook_path(project_path: str | Path = ".") -> Path:
    """Return the default Git pre-commit hook path for an AXON project."""
    return Path(project_path).expanduser().resolve() / ".git" / "hooks" / "pre-commit"


def write_precommit_hook(
    project_path: str | Path = ".",
    *,
    hook_path: str | Path | None = None,
    force: bool = False,
) -> PrecommitInstallResult:
    """Install the AXON pre-commit hook template.

    By default this writes to ``<project>/.git/hooks/pre-commit``. Tests and
    advanced users may pass ``hook_path`` to write the template elsewhere.
    Existing files are preserved unless ``force`` is true.
    """
    project = Path(project_path).expanduser().resolve()
    destination = Path(hook_path).expanduser().resolve() if hook_path is not None else default_hook_path(project)

    if destination.exists() and not force:
        raise PrecommitError(f"pre-commit hook already exists: {destination}; pass --force to overwrite")

    if not destination.parent.exists():
        raise PrecommitError(f"hook directory does not exist: {destination.parent}")

    destination.write_text(render_precommit_hook(), encoding="utf-8")
    current_mode = destination.stat().st_mode
    destination.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return PrecommitInstallResult(
        path=destination,
        installed=True,
        message=f"Installed AXON pre-commit hook: {destination}",
    )


def check_precommit_hook(
    project_path: str | Path = ".",
    *,
    hook_path: str | Path | None = None,
) -> PrecommitInstallResult:
    """Check whether the AXON pre-commit hook is installed and current."""
    project = Path(project_path).expanduser().resolve()
    destination = Path(hook_path).expanduser().resolve() if hook_path is not None else default_hook_path(project)
    if not destination.exists():
        return PrecommitInstallResult(destination, False, f"AXON pre-commit hook not installed: {destination}")
    if destination.read_text(encoding="utf-8") != render_precommit_hook():
        return PrecommitInstallResult(destination, False, f"pre-commit hook differs from AXON template: {destination}")
    if not os.access(destination, os.X_OK):
        return PrecommitInstallResult(destination, False, f"pre-commit hook is not executable: {destination}")
    return PrecommitInstallResult(destination, True, f"AXON pre-commit hook is installed: {destination}")


def run_precommit_checks(
    project_path: str | Path = ".",
    *,
    full: bool = False,
    python_executable: str | None = None,
    include_pytest: bool = True,
) -> PrecommitRunResult:
    """Run deterministic local quality checks for an AXON project.

    The default check set mirrors the fast, dependency-light CI path and avoids
    requiring FastMCP/provider SDKs. Passing ``full=True`` keeps smoke tests in
    the project quality gate.
    """
    project = Path(project_path).expanduser().resolve()
    if not project.exists() or not project.is_dir():
        raise PrecommitError(f"project path is not a directory: {project}")

    executable = python_executable or sys.executable
    checks: list[PrecommitCheckResult] = []

    commands: list[tuple[str, list[str]]] = [
        ("compile", [executable, "-m", "compileall", "-q", "src", "tests"]),
        ("dependency audit", [executable, "-m", "axon", "deps", "."]),
        ("repository hygiene", [executable, "-m", "axon", "hygiene", "."]),
    ]

    project_check = [
        executable,
        "-m",
        "axon",
        "check-project",
        "examples",
        "--snapshot-dir",
        "tests/snapshots/examples",
        "--require-snapshots",
    ]
    if not full:
        project_check.append("--no-smoke")
    commands.append(("project quality gate", project_check))

    for name, command in commands:
        checks.append(_run_command(name, command, project))
        if not checks[-1].passed:
            return PrecommitRunResult(project, checks)

    checks.extend(_run_formatter_smoke_checks(project, executable))
    if checks and not checks[-1].passed:
        return PrecommitRunResult(project, checks)

    if include_pytest:
        checks.append(_run_command("pytest", [executable, "-m", "pytest"], project, capture=False))
    return PrecommitRunResult(project, checks)


def _run_command(name: str, command: Sequence[str], cwd: Path, *, capture: bool = True) -> PrecommitCheckResult:
    env = os.environ.copy()
    src_path = str(cwd / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = src_path if not existing else f"{src_path}{os.pathsep}{existing}"
    completed = subprocess.run(
        list(command),
        cwd=cwd,
        check=False,
        capture_output=capture,
        text=True,
        env=env,
    )
    return PrecommitCheckResult(
        name=name,
        command=list(command),
        returncode=int(completed.returncode),
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
    )


def _run_formatter_smoke_checks(project: Path, executable: str) -> list[PrecommitCheckResult]:
    source = project / "examples" / "hello.ax"
    if not source.exists():
        return [PrecommitCheckResult("formatter smoke", ["<internal>"], 1, stderr=f"missing source: {source}")]

    with tempfile.TemporaryDirectory(prefix="axon_precommit_") as tmpdir:
        formatted = Path(tmpdir) / "hello.formatted.ax"
        env = os.environ.copy()
        src_path = str(project / "src")
        existing = env.get("PYTHONPATH")
        env["PYTHONPATH"] = src_path if not existing else f"{src_path}{os.pathsep}{existing}"

        render_command = [executable, "-m", "axon", "format", str(source)]
        render = subprocess.run(render_command, cwd=project, check=False, capture_output=True, text=True, env=env)
        if render.returncode != 0:
            return [PrecommitCheckResult("formatter render", render_command, int(render.returncode), render.stdout, render.stderr)]
        formatted.write_text(render.stdout, encoding="utf-8")

        check_command = [executable, "-m", "axon", "format", str(formatted), "--check"]
        return [_run_command("formatter idempotency", check_command, project)]
